---
title: ggsample
subtitle: ""
author: "Exploded Examples"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, fig.height = 6, comment = "")
options(knitr.duplicate.label = "allow")
library(ggsample)
```


---

`r flipbookr::chunk_reveal('geom_lm_sample_1', title = '### geom_lm_sample')`

```{r geom_lm_sample_1, include = F}
my_seed <- sample(1:100, 1)
library(ggplot2)
ggplot(data = cars) +
  aes(x = speed, y = dist) +
  geom_point() +
  geom_smooth(method = lm,
             se = FALSE) +
   geom_point_sample(color = "red",
                     seed = my_seed) +
   geom_lm_sample(color = "red",
                  seed = my_seed)
```



---

`r flipbookr::chunk_reveal('geom_point_sample_2', title = '### geom_point_sample')`

```{r geom_point_sample_2, include = F}
# using the function
set.seed(92389)
library(ggplot2)
ggplot(data = cars) +
 aes(x = speed, y = dist) +
 geom_point() +
 geom_point_sample(color = "red") +
 geom_point_sample(color = "green",
                   sample_size = 5) +
 geom_point_sample(sample_size = 2,
                   color = "blue")
```


